import os
import logging
from pathlib import Path
from datetime import datetime
from jinja2 import Environment, FileSystemLoader

from rag.engine import RAGEngine
from rag.comparator import CrossPlatformComparator

logger = logging.getLogger(__name__)

REPORTS_DIR = Path("data/reports")
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

class ReportGenerator:
    """
    Generates Markdown reports summarizing insights on a specific query.
    """
    def __init__(self, rag_engine: RAGEngine, comparator: CrossPlatformComparator):
        self.rag_engine = rag_engine
        self.comparator = comparator
        
        # Set up Jinja2 templates
        template_dir = Path(__file__).parent / "templates"
        template_dir.mkdir(exist_ok=True)
        self._ensure_default_template(template_dir)
        
        self.env = Environment(loader=FileSystemLoader(str(template_dir)))
        self.template = self.env.get_template("report.md.j2")

    def _ensure_default_template(self, template_dir: Path):
        """Creates the default Jinja2 template if it doesn't exist."""
        template_path = template_dir / "report.md.j2"
        if not template_path.exists():
            template_path.write_text("""# Discovery Engine Report
**Generated:** {{ date }}
**Query:** {{ query }}

## 1. Executive Summary
{{ comparison.synthesis_summary }}

## 2. Cross-Platform Similarities
{% for sim in comparison.similarities %}
- {{ sim }}
{% endfor %}

## 3. Key Differences
{% for diff in comparison.differences %}
- {{ diff }}
{% endfor %}

## 4. Platform Quirks
{% for platform, quirk in comparison.platform_quirks.items() %}
- **{{ platform | title }}**: {{ quirk }}
{% endfor %}

## 5. Detailed Platform Insights
{% for platform, answer in platform_answers.items() %}
### {{ platform | title }}
{{ answer }}

{% endfor %}

---
*Generated by the AI-Powered Discovery Engine*
""")

    def generate_report(self, query: str) -> str:
        """
        Runs a cross-platform comparison and generates a Markdown report.
        Returns the path to the generated report file.
        """
        logger.info(f"Generating report for query: '{query}'")
        
        result = self.comparator.compare(question=query)
        
        # Render template
        markdown_content = self.template.render(
            query=query,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            comparison=result.get("comparison", {}),
            platform_answers=result.get("platform_answers", {})
        )
        
        # Save to file
        safe_query = "".join([c if c.isalnum() else "_" for c in query])[:50]
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{safe_query}.md"
        filepath = REPORTS_DIR / filename
        
        filepath.write_text(markdown_content, encoding="utf-8")
        
        logger.info(f"Report saved to {filepath}")
        return str(filepath)
